// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq4SWrR1mH53LfnADKRF_Rw3oLVLsd9ws',
    appId: '1:809645156846:web:2e5c067c4a9c27cb0b86ff',
    messagingSenderId: '809645156846',
    projectId: 'taif-7f2ea',
    authDomain: 'taif-7f2ea.firebaseapp.com',
    storageBucket: 'taif-7f2ea.firebasestorage.app',
    measurementId: 'G-CCS75SJD4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgpd1fjdCXdVCFlreXUrtQFAqwGXAplLE',
    appId: '1:809645156846:android:35391b549c52a28c0b86ff',
    messagingSenderId: '809645156846',
    projectId: 'taif-7f2ea',
    storageBucket: 'taif-7f2ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-WOLpOxbTmnyC0fxiaGMWTO71xF-nCo',
    appId: '1:809645156846:ios:488f531004bd25bb0b86ff',
    messagingSenderId: '809645156846',
    projectId: 'taif-7f2ea',
    storageBucket: 'taif-7f2ea.firebasestorage.app',
    iosBundleId: 'com.example.taif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa-WOLpOxbTmnyC0fxiaGMWTO71xF-nCo',
    appId: '1:809645156846:ios:488f531004bd25bb0b86ff',
    messagingSenderId: '809645156846',
    projectId: 'taif-7f2ea',
    storageBucket: 'taif-7f2ea.firebasestorage.app',
    iosBundleId: 'com.example.taif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq4SWrR1mH53LfnADKRF_Rw3oLVLsd9ws',
    appId: '1:809645156846:web:3362ed4ab4cb5c4f0b86ff',
    messagingSenderId: '809645156846',
    projectId: 'taif-7f2ea',
    authDomain: 'taif-7f2ea.firebaseapp.com',
    storageBucket: 'taif-7f2ea.firebasestorage.app',
    measurementId: 'G-YBXJXJ71SM',
  );

}